export { IconDefinition } from '@fortawesome/free-solid-svg-icons';
export { faAngleDoubleDown } from '@fortawesome/free-solid-svg-icons/faAngleDoubleDown';
export { faBug } from '@fortawesome/free-solid-svg-icons/faBug';
export { faCheck } from '@fortawesome/free-solid-svg-icons/faCheck';
export { faHeart as faHeartOutline } from '@fortawesome/free-regular-svg-icons/faHeart';
export { faHeart as faHeartSolid } from '@fortawesome/free-solid-svg-icons/faHeart';
export { faSortAlphaDown } from '@fortawesome/free-solid-svg-icons/faSortAlphaDown';
export { faSortAlphaDownAlt } from '@fortawesome/free-solid-svg-icons/faSortAlphaDownAlt';
export { faSortAlphaUp } from '@fortawesome/free-solid-svg-icons/faSortAlphaUp';
export { faSortAlphaUpAlt } from '@fortawesome/free-solid-svg-icons/faSortAlphaUpAlt';
export { faSortAmountDown } from '@fortawesome/free-solid-svg-icons/faSortAmountDown';
export { faSortAmountDownAlt } from '@fortawesome/free-solid-svg-icons/faSortAmountDownAlt';
export { faSortAmountUp } from '@fortawesome/free-solid-svg-icons/faSortAmountUp';
export { faSortAmountUpAlt } from '@fortawesome/free-solid-svg-icons/faSortAmountUpAlt';
export { faSortNumericDown } from '@fortawesome/free-solid-svg-icons/faSortNumericDown';
export { faSortNumericDownAlt } from '@fortawesome/free-solid-svg-icons/faSortNumericDownAlt';
export { faSortNumericUp } from '@fortawesome/free-solid-svg-icons/faSortNumericUp';
export { faSortNumericUpAlt } from '@fortawesome/free-solid-svg-icons/faSortNumericUpAlt';
export { faTimes } from '@fortawesome/free-solid-svg-icons/faTimes';
export { faTimesCircle } from '@fortawesome/free-regular-svg-icons/faTimesCircle';
